const WORD_BANK = [
  "airplane",
  "anchor",
  "apple",
  "astronaut",
  "backpack",
  "banana",
  "beach",
  "bicycle",
  "bridge",
  "camera",
  "campfire",
  "candle",
  "castle",
  "cat",
  "chair",
  "clock",
  "cloud",
  "coffee",
  "compass",
  "cookie",
  "crown",
  "diamond",
  "dinosaur",
  "donut",
  "dragon",
  "drum",
  "eagle",
  "elephant",
  "escalator",
  "feather",
  "firetruck",
  "fishing",
  "flashlight",
  "flower",
  "football",
  "forest",
  "fork",
  "giraffe",
  "glasses",
  "guitar",
  "hamburger",
  "hammer",
  "helmet",
  "helicopter",
  "honey",
  "hotdog",
  "ice cream",
  "island",
  "jacket",
  "jellyfish",
  "kangaroo",
  "keyboard",
  "kite",
  "ladder",
  "lantern",
  "laptop",
  "leaf",
  "lightning",
  "lighthouse",
  "lion",
  "lollipop",
  "magnet",
  "microphone",
  "mirror",
  "moon",
  "motorcycle",
  "mountain",
  "mushroom",
  "necklace",
  "octopus",
  "paintbrush",
  "palm tree",
  "pancake",
  "parachute",
  "parrot",
  "passport",
  "penguin",
  "piano",
  "pineapple",
  "pizza",
  "planet",
  "popsicle",
  "present",
  "rabbit",
  "rainbow",
  "rocket",
  "sandwich",
  "satellite",
  "scissors",
  "shark",
  "ship",
  "skateboard",
  "snowman",
  "spider",
  "starfish",
  "strawberry",
  "submarine",
  "suitcase",
  "sunflower",
  "sunglasses",
  "sword",
  "telescope",
  "tent",
  "thunder",
  "toothbrush",
  "tornado",
  "tractor",
  "traffic light",
  "train",
  "treasure",
  "triangle",
  "trophy",
  "trumpet",
  "umbrella",
  "unicorn",
  "vacuum",
  "volcano",
  "wallet",
  "waterfall",
  "whale",
  "windmill",
  "zebra",
];

function shuffle<T>(items: T[]): T[] {
  const copy = [...items];

  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }

  return copy;
}

export function pickRandomWords(count: number): string[] {
  const desired = Math.max(1, Math.min(count, WORD_BANK.length));
  return shuffle(WORD_BANK).slice(0, desired);
}